# Generated by Django 5.2 on 2025-05-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='reserved_seat_ids',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seats',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_reserved', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.flight')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats',
            field=models.ManyToManyField(to='api.seat'),
        ),
    ]
