# Generated by Django 5.2 on 2025-05-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_flight_reserved_seat_ids_remove_reservation_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='reserved_seat_ids',
        ),
    ]
