# Generated by Django 5.2 on 2025-04-26 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='airlines/logos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airline',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
