# Generated by Django 5.2 on 2025-04-27 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_airline_description_airline_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_seats',
            field=models.IntegerField(default=0),  # Change this to 0 or another default number
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=0),  # Change this to 0 or another default number
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airline',
            name='logo',
            field=models.ImageField(upload_to='airlines/'),
        ),
    ]
