# Generated by Django 5.2 on 2025-04-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_flight_available_seats_flight_total_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
    ]
