# Generated by Django 5.2 on 2025-04-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_flight_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
