# Generated by Django 5.2 on 2025-05-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=30),
        ),
    ]
