# Generated by Django 5.2 on 2025-05-17 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_flight_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='flight',
            name='seats',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_list', to='api.flight'),
        ),
    ]
