# Generated by Django 5.2 on 2025-05-17 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_flight_total_seats_flight_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='seats',
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.flight'),
        ),
    ]
