# Generated by Django 5.2.1 on 2025-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_flight_seats_flight_total_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='reserved_seat_ids',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=18),
        ),
    ]
